/**
 * 驾驶舱
 */
import Mock from 'mockjs'

export default [
  {
    url: '/mock/operator/list',
    method: 'get',
    response: () => {
      return Mock.mock({
        code: 200,
        data: [
          {
            componentType: 1,
            componentTypeName: '数据源',
            leafChild: [
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'jed',
                componentNameZh: 'JED',
                componentType: 1,
                componentTypeName: '数据源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\r\n    "type":"object",\r\n    "properties":{\r\n        "url":{\r\n            "title":"域名",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "port":{\r\n            "title":"端口",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "username":{\r\n            "title":"用户名",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "password":{\r\n            "title":"密文密码",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "db":{\r\n            "title":"数据库",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "table":{\r\n            "title":"表名",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        }\r\n    },\r\n    "labelWidth":120,\r\n    "displayType":"row"\r\n}',
                id: 343,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 102,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'localFile',
                componentNameZh: '本地文件',
                componentType: 1,
                componentTypeName: '数据源',
                componentVersion: 1,
                description: '',
                frontendFormSchema: '{}',
                id: 392,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 0,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'hive',
                componentNameZh: 'Hive',
                componentType: 1,
                componentTypeName: '数据源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 8,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 100,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'hdfs',
                componentNameZh: 'HDFS',
                componentType: 1,
                componentTypeName: '数据源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 20,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 101,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
            ],
          },
          {
            componentType: 2,
            componentTypeName: '目标源',
            leafChild: [
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'jed',
                componentNameZh: 'JED',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\r\n    "type":"object",\r\n    "labelWidth":120,\r\n    "displayType":"row",\r\n    "properties":{\r\n        "url":{\r\n            "title":"域名",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "port":{\r\n            "title":"端口",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "username":{\r\n            "title":"用户名",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "password":{\r\n            "title":"密文密码",\r\n            "type":"string",\r\n            "required":true,\r\n            "widget":"password",\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "db":{\r\n            "title":"数据库",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "table":{\r\n            "title":"表名",\r\n            "type":"string",\r\n            "required":true,\r\n            "props":{\r\n\r\n            }\r\n        },\r\n        "saveMode":{\r\n            "title":"写入方式",\r\n            "type":"string",\r\n            "enum":[\r\n                "Append",\r\n                "Overwrite"\r\n            ],\r\n            "enumNames":[\r\n                "追加",\r\n                "覆盖"\r\n            ],\r\n            "widget":"select"\r\n        }\r\n    }\r\n}',
                id: 347,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 102,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'es',
                componentNameZh: 'ES',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n    "type":"object",\n    "labelWidth":156,\n    "displayType":"column",\n    "properties":{\n        "version":{\n            "title":"ES版本",\n            "type":"string",\n            "enum":[\n                "6.x",\n                "7.x"\n            ],\n            "enumNames":[\n                "ES 6.x",\n                "ES 7.x"\n            ],\n            "widget":"radio",\n            "default":"6.x"\n        },\n        "httpHosts":{\n            "title":"集群地址（HTTP）",\n            "type":"string",\n            "required":true,\n            "props":{\n\n            }\n        },\n        "clusterName":{\n            "title":"集群名称",\n            "type":"string",\n            "required":true,\n            "props":{\n\n            }\n        },\n        "user":{\n            "title":"用户名",\n            "type":"string",\n            "required":true,\n            "props":{\n\n            }\n        },\n        "password":{\n            "title":"密码",\n            "type":"string",\n            "required":true,\n            "props":{\n\n            }\n        },\n        "index":{\n            "title":"目标表索引 Index",\n            "type":"string",\n            "required":true,\n            "props":{\n\n            }\n        },\n        "esType":{\n            "title":"目标表类型 Type",\n            "type":"string",\n            "required":true,\n            "props":{\n\n            },\n            "hidden":"{{rootValue.version === \'7.x\'}}"\n        },\n        "numPartitions":{\n            "title":"并行度",\n            "type":"number",\n            "required":true\n        },\n        "isDelFlag":{\n            "title":"写入前清理已有数据",\n            "type":"boolean",\n            "widget":"switch",\n            "required":true,\n            "default":true\n        },\n        "delQueryExpression":{\n            "title":"清理数据条件语句",\n            "type":"string",\n            "format":"textarea",\n            "required":true,\n            "hidden":"{{!rootValue.isDelFlag}}",\n            "props":{\n\n            }\n        },\n        "syncFlag":{\n            "title":"删除执行方式",\n            "type":"string",\n            "enum":[\n                "sync"\n            ],\n            "enumNames":[\n                "同步"\n            ],\n            "widget":"radio",\n            "default":"sync",\n            "hidden":"{{!rootValue.isDelFlag}}"\n        }\n    }\n}',
                id: 356,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 112,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'jdq',
                componentNameZh: 'JDQ',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n\t"type": "object",\n\t"labelWidth": 120,\n\t"displayType": "row",\n\t"properties": {\n\t\t"topic": {\n\t\t\t"title": "topic名称",\n\t\t\t"type": "string",\n\t\t\t"required": true,\n\t\t\t"props": {}\n\t\t},\n\t\t"userOrClientId": {\n\t\t\t"title": "用户名",\n\t\t\t"type": "string",\n\t\t\t"required": true,\n\t\t\t"props": {}\n\t\t},\n\t\t"password": {\n\t\t\t"title": "密码",\n\t\t\t"type": "string",\n\t\t\t"required": true,\n\t\t\t"props": {}\n\t\t},\n\t\t"applicationDomainName": {\n\t\t\t"title": "应用域名",\n\t\t\t"type": "string",\n\t\t\t"required": true,\n\t\t\t"props": {}\n\t\t},\n\t\t"messageType": {\n\t\t\t"title": "消息数据格式",\n\t\t\t"type": "string",\n\t\t\t"enum": ["json", "string"],\n\t\t\t"enumNames": ["json", "string"],\n\t\t\t"widget": "select",\n\t\t\t"default": "json",\n\t\t\t"required": true\n\t\t},\n\t\t"external": {\n\t\t\t"title": "分割方式",\n\t\t\t"type": "string",\n\t\t\t"enum": [",", ";", "\\t", "|", "custom"],\n\t\t\t"enumNames": ["英文逗号(,)", "英文分号(;)", "制表符(Tab)", "单竖线(|)", "自定义"],\n\t\t\t"widget": "select",\n\t\t\t"required": true,\n\t\t\t"hidden": "{{rootValue.messageType===\'json\'}}"\n\t\t},\n\t\t"custom": {\n\t\t\t"title": "自定义分割方式",\n\t\t\t"type": "string",\n\t\t\t"required": true,\n\t\t\t"hidden": "{{rootValue.messageType===\'json\' || rootValue.external !== \'custom\'}}",\n\t\t\t"props": {}\n\t\t}\n\t}\n}',
                id: 342,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 110,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'jmq',
                componentNameZh: 'JMQ',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\r\n  "type": "object",\r\n  "labelWidth": 120,\r\n  "displayType": "row",\r\n  "properties": {\r\n    "topic": {\r\n      "title": "topic名称",\r\n      "type": "string",\r\n      "required": true,\r\n      "props": {}\r\n    },\r\n    "app": {\r\n      "title": "JMQ应用",\r\n      "type": "string",\r\n      "required": true,\r\n      "props": {}\r\n    },\r\n    "password": {\r\n      "title": "密码",\r\n      "type": "string",\r\n      "required": true,\r\n      "props": {}\r\n    },\r\n    "address": {\r\n      "title": "集群地址",\r\n      "type": "string",\r\n      "required": true,\r\n      "props": {}\r\n    },\r\n    "messageType": {\r\n      "title": "消息数据格式",\r\n      "type": "string",\r\n      "enum": [\r\n        "json"\r\n      ],\r\n      "enumNames": [\r\n        "json"\r\n      ],\r\n      "widget": "select",\r\n      "default": "json",\r\n      "required": true\r\n    },\r\n    "external": {\r\n      "title": "分割方式",\r\n      "type": "string",\r\n      "enum": [\r\n        ",",\r\n        ";",\r\n        "\\t",\r\n        "|",\r\n        "custom"\r\n      ],\r\n      "enumNames": [\r\n        "英文逗号(,)",\r\n        "英文分号(;)",\r\n        "制表符(Tab)",\r\n        "单竖线(|)",\r\n        "自定义"\r\n      ],\r\n      "widget": "select",\r\n      "required": true,\r\n      "hidden": "{{rootValue.messageType===\'json\'}}"\r\n    },\r\n    "custom": {\r\n      "title": "自定义分割方式",\r\n      "type": "string",\r\n      "required": true,\r\n      "hidden": "{{rootValue.messageType===\'json\' || rootValue.external !== \'custom\'}}",\r\n      "props": {}\r\n    }\r\n  }\r\n}',
                id: 422,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 0,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'ck',
                componentNameZh: 'CK',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n                      "type":"object",\n                      "labelWidth":162,\n                      "displayType":"row",\n                      "properties":{\n                          "domain":{\n                              "title":"域名",\n                              "type":"string",\n                              "required":true,\n                              "props":{\n\n                              }\n                          },\n                          "ckPort":{\n                              "title":"端口",\n                              "type":"string",\n                              "required":true,\n                              "props":{\n\n                              }\n                          },\n                          "user":{\n                              "title":"用户名",\n                              "type":"string",\n                              "required":true,\n                              "props":{\n\n                              },\n                              "description":"确认用户有读写权限"\n                          },\n                          "password":{\n                              "title":"密码",\n                              "type":"string",\n                              "required":true,\n                              "props":{\n\n                              }\n                          },\n                          "dataBase":{\n                              "title":"目标库",\n                              "type":"string",\n                              "required":true,\n                              "props":{\n\n                              }\n                          },\n                          "tableCluster":{\n                              "title":"目标表",\n                              "type":"string",\n                              "required":true,\n                              "props":{\n\n                              }\n                          },\n                          "batchSize":{\n                              "title":"单批数据条数",\n                              "type":"number",\n                              "default":1,\n                              "required":true,\n                              "props":{\n                                  "addonAfter":"万条",\n                                  "suffix":""\n                              },\n                              "min":1,\n                              "max":100\n                          },\n                          "numPartitions":{\n                              "title":"并行度",\n                              "type":"number",\n                              "required":true,\n                              "props":{\n\n                              },\n                              "min":1,\n                              "max":999\n                          },\n                          "isClearConditonData":{\n                              "title":"写入前清理已有数据",\n                              "type":"boolean",\n                              "widget":"switch",\n                              "description":"请确认有删除表的权限"\n                          },\n                          "clearConditon":{\n                              "title":"删除分区数据",\n                              "type":"string",\n                              "props":{\n                              },\n                              "hidden":"{{!rootValue.isClearConditonData}}",\n                              "required":true\n                          }\n                      }\n                  }',
                id: 352,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 111,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'hdfs',
                componentNameZh: 'HDFS',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 5,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 101,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'hive',
                componentNameZh: 'Hive',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 6,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 100,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'jimdb',
                componentNameZh: 'JimDb',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 7,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 103,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'api',
                componentNameZh: 'Api',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 0,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 301,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 107,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '1',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'hbase',
                componentNameZh: 'HBASE',
                componentType: 2,
                componentTypeName: '目标源',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 125,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 105,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
            ],
          },
          {
            componentType: 3,
            componentTypeName: '计算算子',
            leafChild: [
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'aggregate',
                componentNameZh: 'Aggregate（聚合）',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 12,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 5,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'api',
                componentNameZh: 'Api',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 0,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 290,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 107,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'distinct',
                componentNameZh: 'Distinct（去重）',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 13,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 9,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'na',
                componentNameZh: 'Fill/Replace',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 16,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 8,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'filter',
                componentNameZh: 'Filter（过滤）',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 10,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 2,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'join',
                componentNameZh: 'Join（关联）',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 11,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 3,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'persist',
                componentNameZh: 'Persist',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 17,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 10,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'repartition',
                componentNameZh: 'Repartition',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 14,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 11,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'sql',
                componentNameZh: 'SQL',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema: '{}',
                id: 19,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 6,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'select',
                componentNameZh: 'Select（选择）',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 2,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 1,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'union',
                componentNameZh: 'UNION（合并）',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 9,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 4,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '{}',
                componentNameEn: 'map',
                componentNameZh: 'map算子',
                componentType: 3,
                componentTypeName: '计算算子',
                componentVersion: 1,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 71,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 12,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
            ],
          },
          {
            componentType: 4,
            componentTypeName: '自定义数据源',
            leafChild: [
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: '93d49048949d400eabc63860d9a07179',
                componentNameZh: '新jar包测试',
                componentType: 4,
                componentTypeName: '自定义数据源',
                componentVersion: 1001,
                description: '测',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 257,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 106,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'd4c6eefc575548aa898354de3bb757db',
                componentNameZh: '新jar包测试_copy',
                componentType: 4,
                componentTypeName: '自定义数据源',
                componentVersion: 1003,
                description: '测',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 258,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 106,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'd4b8f3495baf41ed9dc55f0304f3ba22',
                componentNameZh: 'testPipeline仅账号库表',
                componentType: 4,
                componentTypeName: '自定义数据源',
                componentVersion: 1001,
                description: '',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 243,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 106,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: '5955cd860a8a45048c2c95d00d0bac0a',
                componentNameZh: 'testPipeline最新',
                componentType: 4,
                componentTypeName: '自定义数据源',
                componentVersion: 1000,
                description: '测',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 244,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 106,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'acd5677226a548f0aeac4b3a65204767',
                componentNameZh: 'testPipeline最新_copy',
                componentType: 4,
                componentTypeName: '自定义数据源',
                componentVersion: 1003,
                description: '测',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 249,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 106,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: 'd41801f7c68d42078fcb7b94cf0e6702',
                componentNameZh: 'testPipeline最新_copy2',
                componentType: 4,
                componentTypeName: '自定义数据源',
                componentVersion: 1005,
                description: '测',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 251,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 106,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
            ],
          },
          {
            componentType: 5,
            componentTypeName: '自定义目标源',
            leafChild: [
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: '05616aa9517d4351ba45f2521652e25b',
                componentNameZh: '目标源2',
                componentType: 5,
                componentTypeName: '自定义目标源',
                componentVersion: 1001,
                description: '12',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 311,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 109,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
            ],
          },
          {
            componentType: 6,
            componentTypeName: '自定义计算算子',
            leafChild: [
              {
                batchStreamFlag: 0,
                componentEngine: 0,
                componentGroup: 2,
                componentGroupName: '批',
                componentLogic: '',
                componentNameEn: '55ba90786f8b483c9f32a3dbeddf4441',
                componentNameZh: 'test-tongyong',
                componentType: 6,
                componentTypeName: '自定义计算算子',
                componentVersion: 1000,
                description: 'ces1',
                frontendFormSchema:
                  '{\n  "type": "object",\n  "labelWidth": 88,\n  "displayType": "row",\n  "properties": {\n    "parallelism": {\n      "title": "并行度",\n      "type": "number",\n      "min": 1,\n      "max": 32768\n    },\n    "slotSharingGroup": {\n      "title": "共享槽组",\n      "type": "string",\n      "props": {}\n    },\n    "shuffleType": {\n      "title": "重分区模式",\n      "type": "string",\n      "enum": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "enumNames": [\n        "rebalance",\n        "rescale",\n        "forward"\n      ],\n      "widget": "select",\n      "required": false,\n      "default": "forward"\n    },\n    "fieldDetails": {\n      "title": "表字段",\n      "type": "array",\n      "widget": "list2",\n      "items": {\n        "type": "object",\n        "properties": {\n          "name": {\n            "title": "字段名",\n            "type": "string",\n            "props": {},\n            "required": true\n          },\n          "type": {\n            "title": "类型",\n            "type": "string",\n            "enum": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "else"\n            ],\n            "enumNames": [\n              "tinyint",\n              "smallint",\n              "int",\n              "bigint",\n              "float",\n              "double",\n              "boolean",\n              "string",\n              "decimal",\n              "varchar",\n              "char",\n              "binary",\n              "timestamp",\n              "其他"\n            ],\n            "widget": "select",\n            "default": "string",\n            "required": true\n          },\n          "custom": {\n            "title": "自定义类型",\n            "type": "string",\n            "props": {},\n            "disabled": "{{rootValue.type !== ',
                id: 318,
                inputPortMax: 0,
                inputPortMin: 0,
                isPublic: 1,
                isUsed: 1,
                operatorType: 108,
                pipelineType: 0,
                projectSpaceId: 0,
                properties: '',
              },
            ],
          },
        ],
        message: '成功',
        success: true,
      })
    },
  },
]
